# Generated by Django 3.2.2 on 2025-03-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Circle',
            new_name='Feature',
        ),
    ]
